// 데이터 형식(typeDefs) 지정하기 위한 gql 불러오기
import { gql } from 'apollo-server';

// export default 활용해 gql typeDefs 내보내기
const moduleTypedefs_BASE_KSV_ORDER_MST = gql`
    type BASE_QRY_KSV_ORDER_MST {
        ORDER_CD: String
        STYLE_CD: String
        ORDER_TYPE: String
        YY: Int
        SEQ: Int
        TOT_CNT: Int
        ADD_CNT: Int
        AVR_PRICE: Float
        FC_BEF: Float
        FC_PRICE: Float
        MATL_AMT: Float
        ETC_AMT: Float
        COMMISSION: Float
        COMM1: Float
        COMM2: Float
        OVER_FLAG: String
        OVER_QTY: Int
        OVER_AMT: Float
        OVER_BILL: String
        CURR_CD: String
        USD_PRICE: Float
        ORDER_DATE: String
        DUE_DATE: String
        MATL_DUE_DATE: String
        NAT_CD: String
        NAT_NAME: String
        FACTORY_CD: String
        SIZE_GROUP: String
        ORDER_FLAG: String
        SAMPLE_FLAG: String
        MATL_SALE_FLAG: String
        FAC_LC_FLAG: String
        FAC_TT_FLAG: String
        ORDER_STATUS: String
        END_DATETIME: String
        REMARK: String
        REF_ORDER_NO: String
        REF_NO: String
        REF_Q_OUTER: String
        REF_Q_LINER: String
        REF_ORDER_REQ: String
        REF_COLOR1: String
        REF_COLOR2: String
        REF_SIZE1: String
        REF_SIZE2: String
        REF_QTY1: String
        REF_QTY2: String
        MATL_PAY_FLAG: String
        MATL_PAY_USER: String
        MATL_PAY_DATETIME: String
        FC_NEGO_TYPE: String
        STATUS_CD: String
        REG_USER: String
        REG_DATETIME: String
        UPD_USER: String
        UPD_DATETIME: String
        APPROVAL_USER: String
        APPROVAL_DATETIME: String
        brand: String
        season: String
        krw_flag: String
        krw_matl_amt: Float
        margin: Float
        frt_check: String
        category: String
        ORG_DUE_DATE: String
        BUYER_TEAM: String
        SAMPLE_COST_FLAG: String
        DL_FLAG: String
        TRADE_PRICE: Float
        LINE_CHARGE_PRICE: Float
        DUTY: Float
        mid_size1: String
        mid_size2: String
        mid_size3: String
        mid_size4: String
        END_STATUS: String
        FC_PRICE2: Float
        CANCEL_DATETIME: String
        PO_MATL_AMT: Float
        id: Int
        PI_CD: String
        PRICE_TERM: String
        CAPA_M_ETA: String
    }

    input BASE_INPUT_KSV_ORDER_MST {
        ORDER_CD: String
        STYLE_CD: String
        ORDER_TYPE: String
        YY: Int
        SEQ: Int
        TOT_CNT: Int
        ADD_CNT: Int
        AVR_PRICE: Float
        FC_BEF: Float
        FC_PRICE: Float
        MATL_AMT: Float
        ETC_AMT: Float
        COMMISSION: Float
        COMM1: Float
        COMM2: Float
        OVER_FLAG: String
        OVER_QTY: Int
        OVER_AMT: Float
        OVER_BILL: String
        CURR_CD: String
        USD_PRICE: Float
        ORDER_DATE: String
        DUE_DATE: String
        MATL_DUE_DATE: String
        NAT_CD: String
        FACTORY_CD: String
        SIZE_GROUP: String
        ORDER_FLAG: String
        SAMPLE_FLAG: String
        MATL_SALE_FLAG: String
        FAC_LC_FLAG: String
        FAC_TT_FLAG: String
        ORDER_STATUS: String
        END_DATETIME: String
        REMARK: String
        REF_ORDER_NO: String
        REF_NO: String
        REF_Q_OUTER: String
        REF_Q_LINER: String
        REF_ORDER_REQ: String
        REF_COLOR1: String
        REF_COLOR2: String
        REF_SIZE1: String
        REF_SIZE2: String
        REF_QTY1: String
        REF_QTY2: String
        MATL_PAY_FLAG: String
        MATL_PAY_USER: String
        MATL_PAY_DATETIME: String
        FC_NEGO_TYPE: String
        STATUS_CD: String
        REG_USER: String
        REG_DATETIME: String
        UPD_USER: String
        UPD_DATETIME: String
        APPROVAL_USER: String
        APPROVAL_DATETIME: String
        brand: String
        season: String
        krw_flag: String
        krw_matl_amt: Float
        margin: Float
        frt_check: String
        category: String
        ORG_DUE_DATE: String
        BUYER_TEAM: String
        SAMPLE_COST_FLAG: String
        DL_FLAG: String
        TRADE_PRICE: Float
        LINE_CHARGE_PRICE: Float
        DUTY: Float
        mid_size1: String
        mid_size2: String
        mid_size3: String
        mid_size4: String
        END_STATUS: String
        FC_PRICE2: Float
        CANCEL_DATETIME: String
        PO_MATL_AMT: Float
        id: Int
        PI_CD: String
        PRICE_TERM: String
    }
`;

export default moduleTypedefs_BASE_KSV_ORDER_MST;
