// 데이터 형식(typeDefs) 지정하기 위한 gql 불러오기
import { gql } from 'apollo-server';

// export default 활용해 gql typeDefs 내보내기
const moduleTypedefs_BASE_BSV_PLAN_FINISH = gql`
    type BASE_QRY_BSV_PLAN_FINISH {
        plan_seq: Int
        USER_ID: String
        SEQ: Int
        JOB_CD: String
        IN_DATE: String
        BUYER_CD: String
        PO_CD: String
        ORDER_CD: String
        STYLE_CD: String
        STYLE_NAME: String
        QTY: Int
        ACT_QTY: Int
        CONN_QTY: Int
        PRE_ORDER_CD: String
        NR: String
        MW: String
        EMBRO: String
        TP: String
        SP: String
        LTHR: String
        G: String
        W: String
        S: String
        FND: String
        DL: String
        PART_WORK: String
        TPR: Int
        EMBOSSING: String
        WASHING: String
        DOWN: String
        CUT: String
        M_ETA: String
        M_ETA_LIMIT: String
        MD_BAL: Int
        S_ETA: String
        SD: String
        SD_BAL: Int
        KIND: String
        BVT_KIND: String
        BVT_KIND_NAME: String
        FOB: Float
        EXP_CMPT: Float
        REMARK: String
        REMARK_SUB: String
        TIME_CHECK: String
        CUTTING: String
        SEW_INPUT: String
        SEW_FROM: String
        SEW_TO: String
        SEWING: Int
        WORK_HOURS: Float
        STD_DAYS: Float
        LINE_DAYS: Float
        LINE: String
        LINE_START_DATE: String
        LINE_CAPA: Float
        LINE_GRADE: Float
        LINE_FIX: String
        PLAN_FIX: String
        REPEAT_CAPA: Float
        PLAN_USER: String
        END_CONFIRM: String
        END_USER: String
        ORG_SEW_FROM: String
        ORG_SEW_TO: String
        PLAN_REMARK: String
        SD_REMARK: String
        EXFACTRY_DATE: String
        PROD_RATE: Float
        CONFIRMED: String
        STD_SEWING: Float
        LINE_SEWING: Float
        FIXED: Float
        SQ: Float
        PM: Float
        SQ_COM: Float
        ORG_LINE_CAPA: Float
        UPDATE_ITEM: String
        REMARK_PS: String
        TP_KOR: String
        DTP: String
        CAPABOOK_IDX: String
        id: Int
    }

    input BASE_INPUT_BSV_PLAN_FINISH {
        plan_seq: Int
        USER_ID: String
        SEQ: Int
        JOB_CD: String
        IN_DATE: String
        BUYER_CD: String
        PO_CD: String
        ORDER_CD: String
        STYLE_CD: String
        STYLE_NAME: String
        QTY: Int
        ACT_QTY: Int
        CONN_QTY: Int
        PRE_ORDER_CD: String
        NR: String
        MW: String
        EMBRO: String
        TP: String
        SP: String
        LTHR: String
        G: String
        W: String
        S: String
        FND: String
        DL: String
        PART_WORK: String
        TPR: Int
        EMBOSSING: String
        WASHING: String
        DOWN: String
        CUT: String
        M_ETA: String
        M_ETA_LIMIT: String
        MD_BAL: Int
        S_ETA: String
        SD: String
        SD_BAL: Int
        KIND: String
        BVT_KIND: String
        BVT_KIND_NAME: String
        FOB: Float
        EXP_CMPT: Float
        REMARK: String
        REMARK_SUB: String
        TIME_CHECK: String
        CUTTING: String
        SEW_INPUT: String
        SEW_FROM: String
        SEW_TO: String
        SEWING: Int
        WORK_HOURS: Float
        STD_DAYS: Float
        LINE_DAYS: Float
        LINE: String
        LINE_START_DATE: String
        LINE_CAPA: Float
        LINE_GRADE: Float
        LINE_FIX: String
        PLAN_FIX: String
        REPEAT_CAPA: Float
        PLAN_USER: String
        END_CONFIRM: String
        END_USER: String
        ORG_SEW_FROM: String
        ORG_SEW_TO: String
        PLAN_REMARK: String
        SD_REMARK: String
        EXFACTRY_DATE: String
        PROD_RATE: Float
        CONFIRMED: String
        STD_SEWING: Float
        LINE_SEWING: Float
        FIXED: Float
        SQ: Float
        PM: Float
        SQ_COM: Float
        ORG_LINE_CAPA: Float
        UPDATE_ITEM: String
        REMARK_PS: String
        TP_KOR: String
        DTP: String
        CAPABOOK_IDX: String
        id: Int
    }
`;

export default moduleTypedefs_BASE_BSV_PLAN_FINISH;
